import About from './About'
import Allrides from './Allrides'
import AuthLayout from './AuthLayout'
import Carousel from './Carousel'
import Contact from './Contact'
import CreateRide from './CreateRide'
import EditRide from './EditRide'
import Email from './Email'
import Footer from './Footer'
import LandingPage from './Landingpage'
import Loading from './Loading'
import Login from './Login'
import LogoutBtn from './LogoutBtn'
import Navbar from './Navbar'
import Post from './Post'
import PostForm from './PostForm'
import RideCard from './RideCard'
import Signup from './signup'
// import toast from './toast'


export  {Navbar,Footer,Contact,LandingPage,About,AuthLayout,Login,Signup,Post,Allrides,EditRide,CreateRide,Carousel,Email,Loading,LogoutBtn,PostForm,RideCard}