    "quotes"= [
      "Kindness is the language which the deaf can hear and the blind can see. - Mark Twain",
      "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
      "No act of kindness, no matter how small, is ever wasted. - Aesop",
      "We make a living by what we get, but we make a life by what we give. - Winston Churchill",
      "The meaning of life is to find your gift. The purpose of life is to give it away. - Pablo Picasso",
      "Service to others is the rent you pay for your room here on earth. - Muhammad Ali",
      "The greatest gift you can give someone is your time, your attention, your love, and your concern. - Joel Osteen",
      "In a world where you can be anything, be kind. - Unknown",
      "We rise by lifting others. - Robert Ingersoll",
      "Be the reason someone smiles today. - Unknown",
      "You have not lived today until you have done something for someone who can never repay you. - John Bunyan",
      "Kindness is the sunshine in which virtue grows. - Robert Green Ingersoll",
      "To ease another's heartache is to forget one's own. - Abraham Lincoln",
      "The smallest act of kindness is worth more than the grandest intention. - Oscar Wilde",
      "Happiness doesn't result from what we get, but from what we give. - Ben Carson",
      "The only way to have a friend is to be one. - Ralph Waldo Emerson",
      "Kindness is a language that the deaf can hear and the blind can see. - Unknown",
      "Life's most persistent and urgent question is, 'What are you doing for others?' - Martin Luther King Jr.",
      "The best way to cheer yourself up is to try to cheer somebody else up. - Mark Twain",
      "We can't help everyone, but everyone can help someone. - Ronald Reagan",
      "One of the greatest gifts you can give is your time. - Unknown",
      "Kindness is the mark we leave on the world. - Unknown",
      "The true meaning of life is to plant trees, under whose shade you do not expect to sit. - Nelson Henderson",
      "Kindness is the key that opens the heart. - Unknown",
      "The best way to find happiness is to give it. - Unknown",
      "A warm smile is the universal language of kindness. - William Arthur Ward",
      "The fragrance always stays in the hand that gives the rose. - Hada Bejar",
      "Kindness is the glue that holds society together. - Unknown",
      "The world is full of kind people. If you can't find one, be one. - Unknown",
      "Do things for people not because of who they are or what they do in return, but because of who you are. - Harold S. Kushner",
      "Real generosity is doing something nice for someone who will never find out. - Frank A. Clark",
      "The best way to help the poor is to not be one of them. - Unknown",
      "When we give cheerfully and accept gratefully, everyone is blessed. - Maya Angelou",
      "Kindness is free; let's pass it on. - Unknown",
      "The measure of a life, after all, is not its duration, but its donation. - Corrie ten Boom",
      "The greatest wisdom is in realizing that we are all one. - Unknown",
      "You have two hands. One to help yourself, the second to help others. - Audrey Hepburn",
      "The more you give, the more you receive. - Unknown",
      "Kindness is a gift everyone can afford to give. - Unknown",
      "To give pleasure to a single heart by a single act is better than a thousand heads bowing in prayer. - Mahatma Gandhi",
      "You cannot do a kindness too soon, for you never know how soon it will be too late. - Ralph Waldo Emerson",
      "Remember there's no such thing as a small act of kindness. Every act creates a ripple with no logical end. - Scott Adams",
      "If you want happiness for an hour, take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help somebody. - Chinese Proverb",
      "The greatest wealth is to live content with little. - Plato",
      "The best part of life is not just surviving, but thriving with passion, compassion, humor, generosity, and kindness. - Maya Angelou",
      "No one has ever become poor by giving. - Anne Frank",
      "Kindness is the sunshine in which virtue grows. - Robert Green Ingersoll",
      "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
      "Generosity is giving more than you can, and pride is taking less than you need. - Khalil Gibran",
      "The fragrance always stays in the hand that gives the rose. - George William Curtis"
    ]
  